"""Split a cleaned MD file into per-chapter pieces + generate per-chapter HTML.

Detection:
- Primary chapter heading: ^##\s*第[一二三四五六七八九十百千万]+章
- Other major sections (intro/outro chunks): 序 / 前言 / 致谢 / 后记 / 附录
- Front matter (cover, TOC, copyright) goes into a single "intro" chunk
- Back matter goes into a single "outro" chunk

Output (per chunk):
  - <stem>-ch1.md (or -intro / -outro)
  - <stem>-ch1.html (auto-generated by md_to_html.py)

Usage:
  python split_by_chapter.py <path-to-cleaned.md>
  python split_by_chapter.py <path-to-workdir>     # picks up *.cleaned.md
"""
from __future__ import annotations

import re
import subprocess
import sys
from pathlib import Path


# Match primary chapter headings: "## 第X章" (Chinese numerals)
_CHAPTER_RE = re.compile(r"^##\s*第[一二三四五六七八九十百千万]+章")

# Other section markers to keep as separate chunks if found
_OTHER_SECTION_PATTERNS = [
    (re.compile(r"^##\s*序"), "chuxu"),  # 序
    (re.compile(r"^##\s*前言"), "qianyan"),  # 前言
    (re.compile(r"^##\s*致谢"), "zhixie"),  # 致谢
    (re.compile(r"^##\s*后记"), "houji"),  # 后记
    (re.compile(r"^##\s*附录"), "appendix"),
    (re.compile(r"^##\s*参考文献"), "refs"),
]


def find_split_points(lines: list[str]) -> list[tuple[int, str]]:
    """Return [(line_idx, slug), ...] for each major section start.

    line_idx is the index of the heading line itself.
    slug is the file-name slug ('intro', 'ch1', 'chuxu', 'outro', etc.).
    """
    splits: list[tuple[int, str]] = []
    chapter_count = 0
    for i, line in enumerate(lines):
        if _CHAPTER_RE.match(line):
            chapter_count += 1
            splits.append((i, f"ch{chapter_count}"))
            continue
        for pat, slug in _OTHER_SECTION_PATTERNS:
            if pat.match(line):
                splits.append((i, slug))
                break
    return splits, chapter_count


def split_md(text: str) -> list[tuple[str, str]]:
    """Return [(slug, content), ...] for each chunk (intro + chapters + outro)."""
    lines = text.split("\n")
    splits, chapter_count = find_split_points(lines)
    if not splits:
        # No chapters found — single chunk
        return [("full", text)]

    chunks: list[tuple[str, str]] = []
    # Intro: from line 0 up to first split
    first_idx = splits[0][0]
    intro_text = "\n".join(lines[:first_idx]).rstrip()
    if intro_text.strip():
        chunks.append(("intro", intro_text))

    # Each chapter + gaps between
    for i, (idx, slug) in enumerate(splits):
        end_idx = splits[i + 1][0] if i + 1 < len(splits) else len(lines)
        chunk_text = "\n".join(lines[idx:end_idx]).rstrip()
        if chunk_text.strip():
            chunks.append((slug, chunk_text))

    # Outro: if no last chapter and there's trailing content
    if chapter_count > 0:
        last_chapter_end = splits[-1 - 1 + 1][0] if len(splits) > 1 else splits[0][0]
        # Already handled by last chapter's end_idx
        pass

    return chunks


def main() -> int:
    if len(sys.argv) < 2:
        print("Usage: python split_by_chapter.py <path-to-cleaned.md|dir>", file=sys.stderr)
        return 2
    target = Path(sys.argv[1]).resolve()
    if target.is_dir():
        md_files = sorted(target.glob("*.cleaned.md"))
    elif target.suffix == ".md":
        md_files = [target]
    else:
        print(f"Not a .md or dir: {target}", file=sys.stderr)
        return 2
    if not md_files:
        print(f"No .cleaned.md found", file=sys.stderr)
        return 1

    for md_path in md_files:
        text = md_path.read_text(encoding="utf-8")
        chunks = split_md(text)
        print(f"=== {md_path.name} → {len(chunks)} chunks ===")
        for slug, content in chunks:
            # Write MD
            chunk_md_path = md_path.with_name(f"{md_path.stem}-{slug}.md")
            chunk_md_path.write_text(content + "\n", encoding="utf-8")
            print(f"  {slug}: {chunk_md_path.name} ({len(content)} chars)")

            # Generate HTML via md_to_html.py
            html_path = chunk_md_path.with_suffix(".html")
            script_dir = Path(__file__).resolve().parent
            r = subprocess.run(
                [sys.executable, str(script_dir / "md_to_html.py"), str(chunk_md_path)],
                capture_output=True, text=True,
            )
            if r.returncode == 0:
                size_kb = html_path.stat().st_size / 1024
                print(f"    -> {html_path.name} ({size_kb:.0f} KB)")
            else:
                print(f"    HTML generation FAILED: {r.stderr}")

    return 0


if __name__ == "__main__":
    sys.exit(main())
